---
# Supplementary configuration file
- name: change-limit | Create folder
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true
  
- name: change-limit | Add the overriding file
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/systemd/system/mysqld.service.d/override.conf.j2"
    dest: "/etc/systemd/system/mariadb.service.d/override.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true
  
- name: change-limit | Add the limit security file
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/security/limits.conf.j2"
    dest: "/etc/security/limits.conf"
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"
  become: true

- name: change-limit | systemd reload config
  systemd:
    daemon_reload: yes
  become: true
