---
- name: setup_cluster | checking if galera cluster setup
  stat:
    path: "/etc/galera_cluster_configured"
  register: "galera_cluster_configured"

- name: setup_cluster | configuring db server and galera
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/my.cnf.d/server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
  become: true
  when: not galera_cluster_configured.stat.exists

- name: setup_cluster | stopping mysql
  service:
    name: "mysql"
    state: "stopped"
  become: true
  when: not galera_cluster_configured.stat.exists

- name: setup_cluster | killing lingering mysql processes
  command: "pkill mysqld"
  become: true
  ignore_errors: true
  when: not galera_cluster_configured.stat.exists
  
- name: setup_cluster | configuring temp galera config
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/my.cnf.d/temp.server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
  become: true
  when: >
    not galera_cluster_configured.stat.exists and
    inventory_hostname == galera_mysql_master_node

- name: setup_cluster | bootstrapping galera cluster
  command: "/usr/bin/galera_new_cluster"
  become: true
  when: >
    not galera_cluster_configured.stat.exists and
    inventory_hostname == galera_mysql_master_node

- name: setup_cluster | joining galera cluster
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when: >
    not galera_cluster_configured.stat.exists and
    inventory_hostname != galera_mysql_master_node
    
- name: setup_cluster | configuring galera on mysql_master
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/my.cnf.d/server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
  become: true
  when: >
    not galera_cluster_configured.stat.exists and
    inventory_hostname == galera_mysql_master_node

- name: setup_cluster | restarting galera on mysql_master
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when: >
    not galera_cluster_configured.stat.exists and
    inventory_hostname == galera_mysql_master_node

- name: setup_cluster | marking galera cluster as configured
  file:
    path: "/etc/galera_cluster_configured"
    state: "touch"
  become: true
  when: not galera_cluster_configured.stat.exists
