---
- name: unconfig_cluster | unconfiguring galera cluster
  template:
    src: "/etc/ansible/roles/deploy_galera/templates/etc/my.cnf.d/unconfig.server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
  become: true

- name: unconfig_cluster | unconfiguring galera cluster
  file:
    path: "/etc/galera_cluster_configured"
    state: "absent"
  become: true

- name: unconfig_cluster | restarting mysql when reconfiguring galera cluster
  service:
    name: "mysql"
    state: "restarted"
  become: true
