---
# handlers file for deploy_galera
- name: "restart mysql"
  service:
    name: "mysql"
    state: "restarted"
  become: true

- name: "reload mysql"
  service:
    name: "mysql"
    state: "reloaded"
  become: true
